### PR TITLE
fix numbers size

### PR DESCRIPTION
**Pull request by hadi-neon**
The default size for numbers was 0 change it to `currentValue`

image
image

### CODE REVIEW

**Comment by mingsnx** [comment]
Hello~
Yesterday, I got all the same `Size` on the `Android emulator`, so depressed -.-(emoji)

This is the result of testing the text size on `iOS` today
**test code**
```dart
Size _getTextSize(String text) {
  TextPainter painter = TextPainter(
    textDirection: TextDirection.ltr,
    text: TextSpan(
      text: text,
      style: TextStyle(fontSize: 25, fontWeight: FontWeight.w500),
    ),
    textScaleFactor: 1.0,
  );
  painter.layout();
  return painter.size;
}
for (var i = 0; i < 10; i++) {
  log("$i: ${_getTextSize(i.toString())}");
}
```
**test result**
This is the result of my test text `size` measurement on `iOS` got several different `width`
[](https://imgtu.com/i/TjWa3d)

**running widget effect**
[](https://imgtu.com/i/TjW4uq)

> so, I remember why I used `0` as the `Size` of digit
```dart
_getTextSize(isNumber ? "0" : currentValue);
```

**Comment by hadi-neon** [comment]
Hey,
 I'm so sorry I did test all cases.
I did fix the error, you can check it here before merging
https://github.com/hadi-neon/animated_digit

**Comment by mingsnx** [comment]
Debugging results after using 
(https://github.com/hadi-neon/animated_digit/blob/master/lib/src/animated_digit_widget.dart)

**Comment by mingsnx** [comment]
Hi~
I added `autoSize` to meet this need

**Comment by mingsnx** [comment]
[published 3.0.0](https://pub.dev/packages/animated_digit)

**Pull request merged**
